version: "3"

services:
   redis:
    restart: always
    image: bitnami/redis:latest
    volumes:
      - ./redis:/bitnami/redis/data
    ports:
      - 6379  
    environment:
      -  ALLOW_EMPTY_PASSWORD=yes
   mongo:
    restart: always
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
   users:
    build: 
      dockerfile: Dockerfile
      context: ./userService
    ports:
      - 2222:2222
    volumes:
      - /app/node_modules
      - ./userService:/app
    depends_on:
      - mongo
      - redis
    restart: always   
      
    



 
   

  
      
 